# This file contains all the configurations for running the script.
#
# History
#   2019-10-06. First edition by Zhenping

[HYSPLIT]
# working directory for HYSPLIT to write CONTROL file. need write access
WORKING_DIR = "C:\\hysplit4\\working"
# write directory for HYSPLIT output files. need write access (can be anywhere)
TDUMP_DIR = "C:\\Users\\zpyin\\Desktop\\hysplit_runner\\data\\tdump"
# pathname for HYSPLIT executable files
EXE_DIR = "C:\\hysplit4\\exec"
