# This file contains all the configurations for running the script.
#
# History
#   2019-10-06. First edition by Zhenping

[HYSPLIT]
# working directory for HYSPLIT to write CONTROL file. need write access
WORKING_DIR = ""
# write directory for HYSPLIT output files (with write access).
TDUMP_DIR = ""
# pathname for HYSPLIT executable files
EXE_DIR = ""
